### ISSUE TITLE
Use case?

### ISSUE THREAD

**Issue by bubffm** [lukasroegner/homebridge-atvremote#1]
Hi Lukas, not an issue but a question. There‘s a discussion over at SmartApfel about the potential use case for this plugin. I (and others) can only really see very deep integration cases. For my day-to-day ATV integration the shortcuts via Apple TV Remote App work pretty well.

If you feel like it, maybe you could give some hints ;-)
https://forum.smartapfel.de/forum/thread/4584-homebridge-atvremote/?postID=74409#post74409

**Comment by lukasroegner** [comment]
Hi @bubffm, I answered your question on the SmartApfel forum.
